### PR TITLE
Voltage Limits Printout

### PR DESCRIPTION
**Pull request by TRMcKinney**
Add printout to console/serial.txt file when the voltage goes out of limits

### CODE REVIEW

**Comment by TRMcKinney** [comment]
> Add printout to console/serial.txt file when the voltage goes out of limits

Slightly unsure if this is in the right place to ever be activated when needed...?

**Review by angusholder — APPROVED** [review]
I would check with Chris, but IIRC InterpretPackage is the one called every time the machine sends a sample, so this should work

**Comment by TRMcKinney** [comment]
@clongbottom When you get a chance, could you check this out, the Voltage Limits Printout commit

**Comment by clongbottom** [comment]
Looks good to me. Angus already approved right?

**Comment by TRMcKinney** [comment]
> Looks good to me. Angus already approved right?

Yep, just wanted to check its location in the code - can't really test if it works until a the machine misbehaves...

I'll go ahead and merge the branch now then?

**Pull request merged**
